### PR TITLE
Upgrade Terraform to 0.8.8

### PR DESCRIPTION
**Pull request by arkan**
Hey,

Thanks for your Drone plugin. We started using it, however Terraform appeared to be outdated. 

This PR is just a quick upgrade to the latest available Terraform version: 0.8.7 

Cheers

### CODE REVIEW

**Comment by jmccann** [comment]
hehehe.  The question is to use package from alpine or manually control versioning in Dockerfile.  

Recent work was done by @tboerger via #23 to move away from how it used to be managed (which is what you are basically asking to revert back to).

While we discuss the path to go with in the future ... you do have the option of building/hosting your own docker image of the plugin to get the version of terraform you want.

**Comment by arkan** [comment]
Thanks for the answer @jmccann - We are using our own fork for the moment.

**Comment by tboerger** [comment]
Beside that, terraform gets compiled statically compiled working on musl? Since when?

**Comment by tboerger** [comment]
I will update the alpine terraform package now.

**Comment by arkan** [comment]
@tboerger Ideally that would be great if you could derive your image from `golang:1.8-alpine` in order to have an autonomous build process. 
This way, we could easily build new release with a simple push to Github.com and have the build process automatically handled by Docker Hub or Quay.io.

**Comment by tboerger** [comment]
Ideally the terraform package on the alpine repo gets updated... If building it doesn't fail...

**Comment by arkan** [comment]
I'm not sure we want to depend on Alpine to get the terraform package. 
We have very precise needs on the Terraform version and we must be able to control the used version. 
If you choose to go this way, we will have to maintain our own fork I think.

**Comment by tboerger** [comment]
In the end it's the decision of @jmccann. Currently v0.9.0 and v0.8.x fails to build on alpine.

**Comment by arkan** [comment]
Yep sure. I updated our fork to be built from a Golang-alpine image :)

**Comment by tboerger** [comment]
Why are you changing the build process now?

**Comment by jmccann** [comment]
I merged #38 which should address this. Thanks!

**Comment by jmccann** [comment]
FYI, created new docker tag jmccann/drone-terraform:1-0.8.8 for this ...

**Pull request closed without merging**
