### PR TITLE
Add 'terraform validate' command

### PR DESCRIPTION
**Pull request by ewbankkit**
Add `terraform validate` before `terraform plan`.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by ewbankkit** [comment]
Once https://github.com/jmccann/drone-terraform/pull/26 is merged to `master` I can resubmit this for Drone 0.5.

**Comment by jmccann** [comment]
@ewbankkit Thanks!  I'll try to get it merged soon.  Wanted to try to get some other eyes on it but not going to get held up on that either.  😉

**Comment by jmccann** [comment]
@ewbankkit Sorry this took so long.  Just merged my 0.5 updates.  Please rebase and fix conflicts.  Thanks!

**Comment by jmccann** [comment]
I am going to close this PR for now.  Feel free to reopen @ewbankkit if you get around to resolving the conflicts.

**Pull request closed without merging**
