### PR TITLE
Update terraform version to 0.12.0

### PR DESCRIPTION
**Pull request by caioquirino**

### CODE REVIEW

**Comment by caioquirino** [comment]
@jmccann Which drone-terraform plugin version do I need to use? I've created it as 6.0-0.12.0, is it okay? Or do you want me to use a different version?

**Comment by jmccann** [comment]
@caioquirino Don't make changes to `CHANGELOG.md`, ill take care of that when I cut a release

**Comment by caioquirino** [comment]
Hi @jmccann, I reverted the changelog :)

**Comment by jmccann** [comment]
@caioquirino FYI `6.0-0.12.1` released

**Comment by caioquirino** [comment]
Thank you very much @jmccann !

**Pull request merged**
