### PR TITLE
Update to terraform version 0.9.4

### PR DESCRIPTION
**Pull request by msuterski**
Updates TF to version 0.9.4.

TF 0.9.x introduced breaking changes (mostly around remote state).

### CODE REVIEW

**Comment by msuterski** [comment]
To support the new backend types, the init command needs to run on each machine, which require running it on each run in case of the plugin. 

I'm going to file another PR that will add this functionality.

Closing this for now.

**Comment by jmccann** [comment]
Seems #40 may be what you are looking for.  I'm going to try and review it today.

**Comment by msuterski** [comment]
Thanks. #40 is missing a couple of options necessary for the `init` to work as expected. I'll file a PR that adds them and we can think about combining them.

**Comment by jmccann** [comment]
@msuterski May be easier to add comments to #40 to address it there?

**Comment by msuterski** [comment]
#40 is a mix of a couple of things, not necessarily only adding support for the new `init` command. The part for the `init` is just calling it without any options. It would take a couple of comments to request what's done in #41. 

Maybe we could point to #41 or simply merge it to #40?

**Pull request closed without merging**
