### PR TITLE
Install terraform from new package

### PR DESCRIPTION
**Pull request by tboerger**
To avoid the download of untrusted packages I have updated the
Dockerfile to use a package provided by alpine testing repository.

### CODE REVIEW

**Comment by tboerger** [comment]
@bradrydzewski Maybe you want to merge it? Simplifies the image...

**Comment by tboerger** [comment]
What about this? :)

**Comment by jmccann** [comment]
@tboerger Just merged my 0.5 updates.  Seems we have some conflicts now.  Mind updating?

**Comment by tboerger** [comment]
I would do that, but since this branch is part of your repo I'm not allowed to push there ;)

**Comment by jmccann** [comment]
Reinstated access for you.  Sorry about that @tboerger !

**Comment by jmccann** [comment]
Just curious how well alpine repo keeps up with terraform package version.  Related to #29 I see alpine repo has `0.7.12` while `0.8.1` is current latest.

**Comment by tboerger** [comment]
This is up to me because I'm the maintainer. I will update to latest version soon.

**Comment by edwinavalos** [comment]
Ah great. Thanks, I missed this PR when I made mine! I'll close mine out.

**Comment by tboerger** [comment]
I have created a pull request to alpine to get the latest stable terraform version installed through the package at https://github.com/alpinelinux/aports/pull/622

**Pull request merged**
